package com.github.fluorumlabs.disconnect.vaadin.crud;

import com.github.fluorumlabs.disconnect.core.annotations.CustomElement;
import com.github.fluorumlabs.disconnect.core.components.Component;
import com.github.fluorumlabs.disconnect.core.components.HtmlComponentWithItem;
import com.github.fluorumlabs.disconnect.core.observables.ObservableEvent;
import com.github.fluorumlabs.disconnect.core.observables.ObservableValue;
import com.github.fluorumlabs.disconnect.core.utils.LowerCase;
import com.github.fluorumlabs.disconnect.core.utils.Mirrored;
import com.github.fluorumlabs.disconnect.core.utils.SerDes;
import com.github.fluorumlabs.disconnect.vaadin.theme.Themable;
import com.github.fluorumlabs.disconnect.vaadin.theme.ThemeVariant;
import js.lang.external.vaadin.DataProvider;
import js.lang.external.vaadin.crud.CrudElement;
import js.lang.external.vaadin.crud.CrudI18n;
import js.lang.external.vaadin.grid.GridDataProviderParams;
import js.web.dom.Event;

import javax.annotation.Nullable;
import java.util.List;

/**
 * <code>&lt;vaadin-crud&gt;</code> is a Web Component for <a href="https://en.wikipedia.org/wiki/Create,_read,_update_and_delete">CRUD</a> operations.
 *
 * <h3>Quick Start</h3>
 * Assign an array to the <a href="#/elements/vaadin-crud#property-items"><code>items</code></a> property.
 *
 * A grid and an editor will be automatically generated and configured based on the data structure provided.
 *
 * <h4>Example:</h4>
 * <pre><code class="language-html">&lt;vaadin-crud items='[{"name": "John", "surname": "Lennon", "role": "singer"},
 *                       {"name": "Ringo", "surname": "Starr", "role": "drums"}]'&gt;&lt;/vaadin-crud&gt;
 * </code></pre>
 * <h3>Data Provider Function</h3>
 * Otherwise, you can provide a <a href="#/elements/vaadin-crud#property-dataProvider"><code>dataProvider</code></a> function.
 *
 * <h4>Example:</h4>
 * <pre><code class="language-html">&lt;vaadin-crud&gt;&lt;/vaadin-crud&gt;
 * </code></pre>
 * <pre><code class="language-js">const crud = document.querySelector('vaadin-crud');
 * const users = [{'name': 'John', 'surname': 'Lennon', 'role': 'singer'}, ...];
 * crud.dataProvider = function(params, callback) {
 *    const chunk = users.slice(params.page * params.pageSize, params.page * params.pageSize + params.pageSize);
 *    callback(chunk, people.length);
 * };
 * </code></pre>
 * NOTE: The autogenerated editor only supports string types. If you need to handle special cases customizing the editor is discussed below.
 *
 * <h3>Customization</h3>
 * Alternatively you can fully configure the component by using <code>slot</code> names.
 *
 * <table>
 *  <thead>
 *   <tr>
 *    <th>Slot name</th>
 *    <th>Description</th>
 *   </tr>
 *  </thead>
 *  <tbody>
 *   <tr>
 *    <td><code>grid</code></td>
 *    <td>To replace the autogenerated grid with a custom one.</td>
 *   </tr>
 *   <tr>
 *    <td><code>form</code></td>
 *    <td>To replace the autogenerated form.</td>
 *   </tr>
 *   <tr>
 *    <td><code>toolbar</code></td>
 *    <td>To replace the toolbar content. Add an element with the attribure <code>new-button</code> for the new item action.</td>
 *   </tr>
 *  </tbody>
 * </table>
 * <h4>Example:</h4>
 * <pre><code class="language-html">&lt;vaadin-crud items='[{"name": "John", "surname": "Lennon", "role": "singer"},
 *                       {"name": "Ringo", "surname": "Starr", "role": "drums"}]'&gt;
 *
 *   &lt;vaadin-grid slot="grid"&gt;
 *    &lt;vaadin-crud-edit-column&gt;&lt;/vaadin-crud-edit-column&gt;
 *    &lt;vaadin-grid-column&gt;
 *     &lt;template class="header"&gt;Name&lt;/template&gt;&lt;template&gt;[[item.name]]&lt;/template&gt;
 *    &lt;/vaadin-grid-column&gt;
 *    &lt;vaadin-grid-column&gt;
 *     &lt;template class="header"&gt;Surname&lt;/template&gt;&lt;template&gt;[[item.surname]]&lt;/template&gt;
 *    &lt;/vaadin-grid-column&gt;
 *   &lt;/vaadin-grid&gt;
 *
 *   &lt;vaadin-form-layout slot="form"&gt;
 *    &lt;vaadin-text-field label="First" path="name"&gt;&lt;/vaadin-text-field&gt;
 *    &lt;vaadin-text-field label="Surname" path="surname"&gt;&lt;/vaadin-text-field&gt;
 *   &lt;/vaadin-form-layout&gt;
 *
 *   &lt;div slot="footer"&gt;Total singers: [[size]]&lt;/div&gt;
 *
 *   &lt;button slot="new"&gt;New singer&lt;/button&gt;
 * &lt;/vaadin-crud&gt;
 * </code></pre>
 * <h3>Helpers</h3>
 * The following elements are used to autoconfigure the grid and the editor
 *
 * <ul>
 *  <li><a href="#/elements/vaadin-crud-grid"><code>&lt;vaadin-crud-grid&gt;</code></a></li>
 *  <li><a href="#/elements/vaadin-crud-edit-column"><code>&lt;vaadin-crud-edit-column&gt;</code></a></li>
 *  <li><a href="#/elements/vaadin-crud-form"><code>&lt;vaadin-crud-form&gt;</code></a></li>
 * </ul>
 * <h3>Styling</h3>
 * The following shadow DOM parts are available for styling:
 *
 * <table>
 *  <thead>
 *   <tr>
 *    <th>Part name</th>
 *    <th>Description</th>
 *   </tr>
 *  </thead>
 *  <tbody>
 *   <tr>
 *    <td><code>toolbar</code></td>
 *    <td>Toolbar container at the bottom. By default it contains the the <code>new</code> button</td>
 *   </tr>
 *  </tbody>
 * </table>
 * The following custom properties are available:
 *
 * <table>
 *  <thead>
 *   <tr>
 *    <th>Custom Property</th>
 *    <th>Description</th>
 *    <th>Default</th>
 *   </tr>
 *  </thead>
 *  <tbody>
 *   <tr>
 *    <td>--vaadin-crud-editor-max-height</td>
 *    <td>max height of editor when opened on the bottom</td>
 *    <td>40%</td>
 *   </tr>
 *   <tr>
 *    <td>--vaadin-crud-editor-max-width</td>
 *    <td>max width of editor when opened on the side</td>
 *    <td>40%</td>
 *   </tr>
 *  </tbody>
 * </table>
 * See <a href="https://github.com/vaadin/vaadin-themable-mixin/wiki">ThemableMixin â€“ how to apply styles for shadow parts</a>
 *
 * <strong>Mixins:</strong> ElementMixin, ThemableMixin, ElementMixin
 *
 * <h2>Example</h2>
 * <pre><code class="language-javascript">demo/index.html
 * </code></pre>
 */
@CustomElement(tagName = "vaadin-crud", external = true)
public class Crud<T> extends HtmlComponentWithItem<T, CrudElement<Mirrored<T>>> implements Themable<CrudElement<Mirrored<T>>> {

    public Crud() {
    }

    public Crud(String textContent) {
        super(textContent);
    }

    public Crud(Component<?>... components) {
        super(components);
    }

    public Crud(Class<T> tClass) {
        super(tClass);
    }

    public Crud(Class<T> tClass, String textContent) {
        super(tClass, textContent);
    }

    public Crud(Class<T> tClass, Component<?>... components) {
        super(tClass, components);
    }

    // !wca! get dataProvider: CrudDataProvider | undefined

    // !wca! set dataProvider: CrudDataProvider | undefined
    /**
     * Function that provides items lazily. Receives arguments <code>params</code>, <code>callback</code>
     *
     * <code>params.page</code> Requested page index
     * <code>params.pageSize</code> Current page size
     * <code>params.filters</code> Currently applied filters
     * <code>params.sortOrders</code> Currently applied sorting orders
     *
     * <code>callback(items, size)</code> Callback function with arguments:
     *  - <code>items</code> Current page of items
     *  - <code>size</code> Total number of items
     * @param value
     */
    public void setDataProvider(@Nullable DataProvider<GridDataProviderParams<Mirrored<T>>, Mirrored<T>> value) {
        getElement().setDataProvider(value);
    }

    // !wca! observe dataProvider: CrudDataProvider | undefined

    // !wca! get editOnClick: boolean
    /**
     * Enables user to click on row to edit it.
     * Note: When enabled, autogenerated grid won't show the edit column.
     */
    public boolean isEditOnClick() {
        return getElement().isEditOnClick();
    }

    // !wca! set editOnClick: boolean
    /**
     * Enables user to click on row to edit it.
     * Note: When enabled, autogenerated grid won't show the edit column.
     */
    public void setEditOnClick(boolean value) {
        getElement().setEditOnClick(value);
    }

    // !wca! observe editOnClick: boolean

    // !wca! get editedItem: CrudItem | undefined
    /**
     * The item being edited in the dialog.
     */
    public @Nullable T getEditedItem() {
        return SerDes.deserialize(getElement().getEditedItem(), getItemClass());
    }

    // !wca! set editedItem: CrudItem | undefined
    /**
     * The item being edited in the dialog.
     */
    public void setEditedItem(@Nullable T value) {
        getElement().setEditedItem(SerDes.mirror(value));
    }

    // !wca! observe editedItem: CrudItem | undefined
    /**
     * The item being edited in the dialog.
     */
    public ObservableValue<T> editedItem() {
        return createObservableValue(this::getEditedItem, this::setEditedItem, "edited-item-changed");
    }

    // !wca! get editorOpened: boolean
    /**
     * Reflects the opened status of the editor.
     */
    public boolean isEditorOpened() {
        return getElement().isEditorOpened();
    }

    // !wca! set editorOpened: boolean
    /**
     * Reflects the opened status of the editor.
     */
    public void setEditorOpened(boolean value) {
        getElement().setEditorOpened(value);
    }

    // !wca! observe editorOpened: boolean
    /**
     * Reflects the opened status of the editor.
     */
    public ObservableValue<Boolean> editorOpened() {
        return createObservableValue(this::isEditorOpened, this::setEditorOpened, "editor-opened-changed");
    }

    // !wca! get editorPosition: !CrudEditorPosition
    /**
     * Sets how editor will be presented on desktop screen.
     *
     * Accepted values are:
     *  - `` (default) - form will open as overlay
     *  - <code>bottom</code> - form will open below the grid
     *  - <code>aside</code> - form will open on the grid side (<em>right</em>, if lft and <em>left</em> if rtl)
     */
    public EditorPosition getEditorPosition() {
        return LowerCase.parse(EditorPosition.class, getElement().getEditorPosition());
    }

    // !wca! set editorPosition: !CrudEditorPosition
    /**
     * Sets how editor will be presented on desktop screen.
     *
     * Accepted values are:
     *  - `` (default) - form will open as overlay
     *  - <code>bottom</code> - form will open below the grid
     *  - <code>aside</code> - form will open on the grid side (<em>right</em>, if lft and <em>left</em> if rtl)
     */
    public void setEditorPosition(EditorPosition value) {
        getElement().setEditorPosition(LowerCase.of(value));
    }

    // !wca! observe editorPosition: !CrudEditorPosition

    // !wca! get exclude: string
    /**
     * A comma-separated list of fields to be excluded from the generated grid and the generated editor.
     *
     * When <a href="#/elements/vaadin-crud#property-include"><code>include</code></a> is defined, this parameter is ignored.
     *
     * Default is to exclude all private fields (those properties starting with underscore)
     */
    public String getExclude() {
        return getElement().getExclude();
    }

    // !wca! set exclude: string
    /**
     * A comma-separated list of fields to be excluded from the generated grid and the generated editor.
     *
     * When <a href="#/elements/vaadin-crud#property-include"><code>include</code></a> is defined, this parameter is ignored.
     *
     * Default is to exclude all private fields (those properties starting with underscore)
     */
    public void setExclude(String value) {
        getElement().setExclude(value);
    }

    // !wca! observe exclude: string

    // !wca! get i18n: !CrudI18n

    // !wca! set i18n: !CrudI18n
    /**
     * The object used to localize this component.
     * For changing the default localization, change the entire
     * <em>i18n</em> object or just the property you want to modify.
     *
     * The object has the following JSON structure and default values:
     *
     * {
     *  newItem: 'New item',
     *  editItem: 'Edit item',
     *  saveItem: 'Save',
     *  cancel: 'Cancel',
     *  deleteItem: 'Delete...',
     *  editLabel: 'Edit',
     *  confirm: {
     *  delete: {
     *  title: 'Confirm delete',
     *  content: 'Are you sure you want to delete the selected item? This action cannot be undone.',
     *  button: {
     *  confirm: 'Delete',
     *  dismiss: 'Cancel'
     *  }
     *  },
     *  cancel: {
     *  title: 'Unsaved changes',
     *  content: 'There are unsaved modifications to the item.',
     *  button: {
     *  confirm: 'Discard',
     *  dismiss: 'Continue editing'
     *  }
     *  }
     *  }
     * }
     */
    public void setI18n(CrudI18n value) {
        getElement().setI18n(value);
    }

    // !wca! observe i18n: !CrudI18n

    // !wca! get include: string
    /**
     * A comma-separated list of fields to include in the generated grid and the generated editor.
     *
     * It can be used to explicitly define the field order.
     *
     * When it is defined <a href="#/elements/vaadin-crud#property-exclude"><code>exclude</code></a> is ignored.
     *
     * Default is undefined meaning that all properties in the object should be mapped to fields.
     */
    public String getInclude() {
        return getElement().getInclude();
    }

    // !wca! set include: string
    /**
     * A comma-separated list of fields to include in the generated grid and the generated editor.
     *
     * It can be used to explicitly define the field order.
     *
     * When it is defined <a href="#/elements/vaadin-crud#property-exclude"><code>exclude</code></a> is ignored.
     *
     * Default is undefined meaning that all properties in the object should be mapped to fields.
     */
    public void setInclude(String value) {
        getElement().setInclude(value);
    }

    // !wca! observe include: string

    // !wca! get items: Array<!CrudItem> | undefined
    /**
     * An array containing the items which will be stamped to the column template instances.
     */
    @Nullable
    public List<T> getItems() {
        return SerDes.unmirrorList(getElement().getItems(), getItemClass());
    }

    // !wca! set items: Array<!CrudItem> | undefined
    /**
     * An array containing the items which will be stamped to the column template instances.
     */
    public void setItems(@Nullable List<T> value) {
        getElement().setItems(SerDes.mirror(value).cast());
    }

    // !wca! observe items: Array<!CrudItem> | undefined
    /**
     * An array containing the items which will be stamped to the column template instances.
     */
    public ObservableValue<List<T>> items() {
        return createObservableValue(this::getItems, this::setItems, "items-changed");
    }

    // !wca! get noFilter: boolean
    /**
     * Disable filtering when grid is autoconfigured.
     */
    public boolean isNoFilter() {
        return getElement().isNoFilter();
    }

    // !wca! set noFilter: boolean
    /**
     * Disable filtering when grid is autoconfigured.
     */
    public void setNoFilter(boolean value) {
        getElement().setNoFilter(value);
    }

    // !wca! observe noFilter: boolean

    // !wca! get noHead: boolean
    /**
     * Remove grid headers when it is autoconfigured.
     */
    public boolean isNoHead() {
        return getElement().isNoHead();
    }

    // !wca! set noHead: boolean
    /**
     * Remove grid headers when it is autoconfigured.
     */
    public void setNoHead(boolean value) {
        getElement().setNoHead(value);
    }

    // !wca! observe noHead: boolean

    // !wca! get noSort: boolean
    /**
     * Disable sorting when grid is autoconfigured.
     */
    public boolean isNoSort() {
        return getElement().isNoSort();
    }

    // !wca! set noSort: boolean
    /**
     * Disable sorting when grid is autoconfigured.
     */
    public void setNoSort(boolean value) {
        getElement().setNoSort(value);
    }

    // !wca! observe noSort: boolean

    // !wca! get size: number
    /**
     * Number of items in the data set which is reported by the grid.
     * Typically it reflects the number of filtered items displayed in the grid.
     */
    public int getSize() {
        return getElement().getSize();
    }

    // !wca! set size: number
    /**
     * Number of items in the data set which is reported by the grid.
     * Typically it reflects the number of filtered items displayed in the grid.
     */
    public void setSize(int value) {
        getElement().setSize(value);
    }

    // !wca! observe size: number

    // !wca! get theme: string | null | undefined

    // !wca! observe theme: string | null | undefined

    // !wca! event cancel: ?
    public ObservableEvent<Event> cancelEvent() {
        return createEvent("cancel");
    }

    // !wca! event delete: ?
    public ObservableEvent<Event> deleteEvent() {
        return createEvent("delete");
    }

    // !wca! event save: ?
    public ObservableEvent<Event> saveEvent() {
        return createEvent("save");
    }

    public enum EditorPosition {
        DEFAULT {
            @Override
            public String toString() {
                return "";
            }
        }, BOTTOM, ASIDE
    }

    public enum Variant implements ThemeVariant {
        NO_BORDER
    }
}
